In [458]:
# Read Datafrom pickle file
import pickle
import pandas as pd
PAK_bowler_df = pickle.load(open('PAK_bowlers_final_df.pkl', 'rb'))
PAK_bowler_df

,Match ID,Date,Venue,Winner,Bowler,Runs Concided,Ball Bowled,Opponent Team,Inning,Over Bowled,Economy Range,Wicket Range
0,225263,2006-08-28,County Ground,Pakistan,Abdul Razzaq,30,24,England,1st Inning,Over: 4,Economy: 6-8,Wickets: 2-3
4,225263,2006-08-28,County Ground,Pakistan,Mohammad Asif,21,24,England,1st Inning,Over: 4,Economy: 0-6,Wickets: 2-3
5,225263,2006-08-28,County Ground,Pakistan,Naved-ul-Hasan,26,25,England,1st Inning,Over: 4,Economy: 6-8,Wickets: 0-1
9,225263,2006-08-28,County Ground,Pakistan,Shahid Afridi,28,26,England,1st Inning,Over: 4,Economy: 6-8,Wickets: 0-1
10,225263,2006-08-28,County Ground,Pakistan,Shoaib Akhtar,31,24,England,1st Inning,Over: 4,Economy: 6-8,Wickets: 0-1
...,...,...,...,...,...,...,...,...,...,...,...,...
2412,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Imad Wasim,25,19,Afghanistan,2nd Inning,Over: 3,Economy: 8-10,Wickets: 0-1
2415,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Mohammad Nawaz,11,6,Afghanistan,2nd Inning,Over: 1,Economy: 10+,Wickets: 0-1
2416,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Mohammad Wasim,13,18,Afghanistan,2nd Inning,Over: 3,Economy: 0-6,Wickets: 0-1
2419,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Shadab Khan,13,25,Afghanistan,2nd Inning,Over: 4,Economy: 0-6,Wickets: 2-3
2420,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Zaman Khan,20,23,Afghanistan,2nd Inning,Over: 3,Economy: 6-8,Wickets: 0-1

In [459]:
# Number of total bowlers we have
bowler_list = PAK_bowler_df['Bowler'].unique()
len(bowler_list)

62

In [460]:
PAK_bowler_df[PAK_bowler_df.columns].dtypes

Match ID                 object
Date             datetime64[ns]
Venue                    object
Winner                   object
Bowler                   object
Runs Concided            object
Ball Bowled              object
Opponent Team            object
Inning                   object
Over Bowled              object
Economy Range            object
Wicket Range             object
dtype: object

In [417]:
## filtering bowlers who are not playing after 2020
last_appearance_date = pd.to_datetime('2021-01-01')
filtered_df = PAK_bowler_df.groupby('Bowler').filter(lambda x: x['Date'].max() > last_appearance_date)
filtered_df

,Match ID,Date,Venue,Winner,Bowler,Runs Concided,Ball Bowled,Opponent Team,Inning,Over Bowled,Economy Range,Wicket Range
16,287855,2007-09-12,Kingsmead,Pakistan,Mohammad Hafeez,24,25,Scotland,2nd Inning,Over: 4,Economy: 0-6,Wickets: 0-1
19,287855,2007-09-12,Kingsmead,Pakistan,Shoaib Malik,3,6,Scotland,2nd Inning,Over: 1,Economy: 0-6,Wickets: 0-1
25,287868,2007-09-17,New Wanderers Stadium,Pakistan,Mohammad Hafeez,46,26,Sri Lanka,2nd Inning,Over: 4,Economy: 10+,Wickets: 0-1
37,287870,2007-09-18,New Wanderers Stadium,Pakistan,Mohammad Hafeez,31,24,Australia,1st Inning,Over: 4,Economy: 6-8,Wickets: 0-1
47,287875,2007-09-20,Newlands,Pakistan,Mohammad Hafeez,27,19,Bangladesh,1st Inning,Over: 3,Economy: 8-10,Wickets: 2-3
...,...,...,...,...,...,...,...,...,...,...,...,...
2412,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Imad Wasim,25,19,Afghanistan,2nd Inning,Over: 3,Economy: 8-10,Wickets: 0-1
2415,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Mohammad Nawaz,11,6,Afghanistan,2nd Inning,Over: 1,Economy: 10+,Wickets: 0-1
2416,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Mohammad Wasim,13,18,Afghanistan,2nd Inning,Over: 3,Economy: 0-6,Wickets: 0-1
2419,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Shadab Khan,13,25,Afghanistan,2nd Inning,Over: 4,Economy: 0-6,Wickets: 2-3
2420,1362817,2023-03-27,Sharjah Cricket Stadium,Pakistan,Zaman Khan,20,23,Afghanistan,2nd Inning,Over: 3,Economy: 6-8,Wickets: 0-1

In [418]:
PAK_bowler_df = filtered_df

In [419]:
matches_played_by_bowler = PAK_bowler_df.groupby('Bowler')['Match ID'].nunique()
matches_played_by_bowler.sort_values(ascending=False).head(10)
# list of top 10 bowlers
top10_bowler_list = matches_played_by_bowler.sort_values(ascending=False).head(10).index
top10_bowler_list

Index(['Shadab Khan', 'Mohammad Hafeez', 'Imad Wasim', 'Haris Rauf',
       'Shaheen Shah Afridi', 'Hasan Ali', 'Faheem Ashraf', 'Shoaib Malik',
       'Mohammad Nawaz', 'Mohammad Hasnain'],
      dtype='object', name='Bowler')

In [420]:
# where winner is pakitan assign Won else Lost
PAK_bowler_df['Winner'] = PAK_bowler_df['Winner'].apply(lambda x: 'Won' if x == 'Pakistan' else 'Lost')
PAK_bowler_df

,Match ID,Date,Venue,Winner,Bowler,Runs Concided,Ball Bowled,Opponent Team,Inning,Over Bowled,Economy Range,Wicket Range
16,287855,2007-09-12,Kingsmead,Won,Mohammad Hafeez,24,25,Scotland,2nd Inning,Over: 4,Economy: 0-6,Wickets: 0-1
19,287855,2007-09-12,Kingsmead,Won,Shoaib Malik,3,6,Scotland,2nd Inning,Over: 1,Economy: 0-6,Wickets: 0-1
25,287868,2007-09-17,New Wanderers Stadium,Won,Mohammad Hafeez,46,26,Sri Lanka,2nd Inning,Over: 4,Economy: 10+,Wickets: 0-1
37,287870,2007-09-18,New Wanderers Stadium,Won,Mohammad Hafeez,31,24,Australia,1st Inning,Over: 4,Economy: 6-8,Wickets: 0-1
47,287875,2007-09-20,Newlands,Won,Mohammad Hafeez,27,19,Bangladesh,1st Inning,Over: 3,Economy: 8-10,Wickets: 2-3
...,...,...,...,...,...,...,...,...,...,...,...,...
2412,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Imad Wasim,25,19,Afghanistan,2nd Inning,Over: 3,Economy: 8-10,Wickets: 0-1
2415,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Mohammad Nawaz,11,6,Afghanistan,2nd Inning,Over: 1,Economy: 10+,Wickets: 0-1
2416,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Mohammad Wasim,13,18,Afghanistan,2nd Inning,Over: 3,Economy: 0-6,Wickets: 0-1
2419,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Shadab Khan,13,25,Afghanistan,2nd Inning,Over: 4,Economy: 0-6,Wickets: 2-3
2420,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Zaman Khan,20,23,Afghanistan,2nd Inning,Over: 3,Economy: 6-8,Wickets: 0-1

In [421]:
PAK_bowler_df.rename(columns = {'Winner':'Win/Lost'}, inplace = True)
PAK_bowler_df

,Match ID,Date,Venue,Win/Lost,Bowler,Runs Concided,Ball Bowled,Opponent Team,Inning,Over Bowled,Economy Range,Wicket Range
16,287855,2007-09-12,Kingsmead,Won,Mohammad Hafeez,24,25,Scotland,2nd Inning,Over: 4,Economy: 0-6,Wickets: 0-1
19,287855,2007-09-12,Kingsmead,Won,Shoaib Malik,3,6,Scotland,2nd Inning,Over: 1,Economy: 0-6,Wickets: 0-1
25,287868,2007-09-17,New Wanderers Stadium,Won,Mohammad Hafeez,46,26,Sri Lanka,2nd Inning,Over: 4,Economy: 10+,Wickets: 0-1
37,287870,2007-09-18,New Wanderers Stadium,Won,Mohammad Hafeez,31,24,Australia,1st Inning,Over: 4,Economy: 6-8,Wickets: 0-1
47,287875,2007-09-20,Newlands,Won,Mohammad Hafeez,27,19,Bangladesh,1st Inning,Over: 3,Economy: 8-10,Wickets: 2-3
...,...,...,...,...,...,...,...,...,...,...,...,...
2412,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Imad Wasim,25,19,Afghanistan,2nd Inning,Over: 3,Economy: 8-10,Wickets: 0-1
2415,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Mohammad Nawaz,11,6,Afghanistan,2nd Inning,Over: 1,Economy: 10+,Wickets: 0-1
2416,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Mohammad Wasim,13,18,Afghanistan,2nd Inning,Over: 3,Economy: 0-6,Wickets: 0-1
2419,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Shadab Khan,13,25,Afghanistan,2nd Inning,Over: 4,Economy: 0-6,Wickets: 2-3
2420,1362817,2023-03-27,Sharjah Cricket Stadium,Won,Zaman Khan,20,23,Afghanistan,2nd Inning,Over: 3,Economy: 6-8,Wickets: 0-1

In [422]:
total_matches = PAK_bowler_df["Match ID"].unique().shape[0]
total_matches

195

In [423]:
#number of matches with every team
matches_with_teams = PAK_bowler_df.groupby('Opponent Team')['Match ID'].nunique()
matches_with_teams

Opponent Team
Afghanistan              6
Australia               19
Bangladesh              16
England                 23
Hong Kong                1
ICC World XI             3
India                    9
Ireland                  1
Kenya                    1
Namibia                  1
Netherlands              2
New Zealand             30
Scotland                 4
South Africa            21
Sri Lanka               22
United Arab Emirates     1
West Indies             18
Zimbabwe                17
Name: Match ID, dtype: int64

In [424]:
# drop column mathch id and date
PAK_bowler_df.drop(['Match ID', 'Date'], axis=1, inplace=True)
PAK_bowler_df

,Venue,Win/Lost,Bowler,Runs Concided,Ball Bowled,Opponent Team,Inning,Over Bowled,Economy Range,Wicket Range
16,Kingsmead,Won,Mohammad Hafeez,24,25,Scotland,2nd Inning,Over: 4,Economy: 0-6,Wickets: 0-1
19,Kingsmead,Won,Shoaib Malik,3,6,Scotland,2nd Inning,Over: 1,Economy: 0-6,Wickets: 0-1
25,New Wanderers Stadium,Won,Mohammad Hafeez,46,26,Sri Lanka,2nd Inning,Over: 4,Economy: 10+,Wickets: 0-1
37,New Wanderers Stadium,Won,Mohammad Hafeez,31,24,Australia,1st Inning,Over: 4,Economy: 6-8,Wickets: 0-1
47,Newlands,Won,Mohammad Hafeez,27,19,Bangladesh,1st Inning,Over: 3,Economy: 8-10,Wickets: 2-3
...,...,...,...,...,...,...,...,...,...,...
2412,Sharjah Cricket Stadium,Won,Imad Wasim,25,19,Afghanistan,2nd Inning,Over: 3,Economy: 8-10,Wickets: 0-1
2415,Sharjah Cricket Stadium,Won,Mohammad Nawaz,11,6,Afghanistan,2nd Inning,Over: 1,Economy: 10+,Wickets: 0-1
2416,Sharjah Cricket Stadium,Won,Mohammad Wasim,13,18,Afghanistan,2nd Inning,Over: 3,Economy: 0-6,Wickets: 0-1
2419,Sharjah Cricket Stadium,Won,Shadab Khan,13,25,Afghanistan,2nd Inning,Over: 4,Economy: 0-6,Wickets: 2-3
2420,Sharjah Cricket Stadium,Won,Zaman Khan,20,23,Afghanistan,2nd Inning,Over: 3,Economy: 6-8,Wickets: 0-1

In [425]:
home_venue = ['Gaddafi Stadium','National Stadium','Rawalpindi Cricket Stadium','Dubai International Cricket Stadium','Sharjah Cricket Stadium']

In [426]:
# if venue is in home_venue assign Home else Oversea
PAK_bowler_df['Venue'] = PAK_bowler_df['Venue'].apply(lambda x: 'Home' if x in home_venue else 'Oversea')
PAK_bowler_df

,Venue,Win/Lost,Bowler,Runs Concided,Ball Bowled,Opponent Team,Inning,Over Bowled,Economy Range,Wicket Range
16,Oversea,Won,Mohammad Hafeez,24,25,Scotland,2nd Inning,Over: 4,Economy: 0-6,Wickets: 0-1
19,Oversea,Won,Shoaib Malik,3,6,Scotland,2nd Inning,Over: 1,Economy: 0-6,Wickets: 0-1
25,Oversea,Won,Mohammad Hafeez,46,26,Sri Lanka,2nd Inning,Over: 4,Economy: 10+,Wickets: 0-1
37,Oversea,Won,Mohammad Hafeez,31,24,Australia,1st Inning,Over: 4,Economy: 6-8,Wickets: 0-1
47,Oversea,Won,Mohammad Hafeez,27,19,Bangladesh,1st Inning,Over: 3,Economy: 8-10,Wickets: 2-3
...,...,...,...,...,...,...,...,...,...,...
2412,Home,Won,Imad Wasim,25,19,Afghanistan,2nd Inning,Over: 3,Economy: 8-10,Wickets: 0-1
2415,Home,Won,Mohammad Nawaz,11,6,Afghanistan,2nd Inning,Over: 1,Economy: 10+,Wickets: 0-1
2416,Home,Won,Mohammad Wasim,13,18,Afghanistan,2nd Inning,Over: 3,Economy: 0-6,Wickets: 0-1
2419,Home,Won,Shadab Khan,13,25,Afghanistan,2nd Inning,Over: 4,Economy: 0-6,Wickets: 2-3
2420,Home,Won,Zaman Khan,20,23,Afghanistan,2nd Inning,Over: 3,Economy: 6-8,Wickets: 0-1

In [453]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [428]:
# Columns for transactions
columns_for_transactions = ["Venue", "Win/Lost", "Bowler", "Opponent Team", "Economy Range", "Over Bowled", "Inning", "Wicket Range"]

# Convert the "Bowler" column to a list of lists
bowler_transactions = PAK_bowler_df["Bowler"].apply(lambda x: [x]).tolist()

# Combine the transactions with the rest of the columns
transactions = [row[1:] + bowler for row, bowler in zip(PAK_bowler_df[columns_for_transactions].values.tolist(), bowler_transactions)]

# Convert all elements in transactions to strings
transactions = [[str(item) for item in transaction] for transaction in transactions]

# Convert the transactions into a one-hot encoded DataFrame
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

# Apply Apriori algorithm to find frequent itemsets
frequent_itemsets = apriori(df_encoded, min_support=0.005, use_colnames=True)

# Generate association rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

In [454]:
bowler_list

array(['Abdul Razzaq', 'Mohammad Asif', 'Naved-ul-Hasan', 'Shahid Afridi',
       'Shoaib Akhtar', 'Mohammad Hafeez', 'Shoaib Malik', 'Umar Gul',
       'Yasir Arafat', 'Sohail Tanvir', 'Fawad Alam', 'Iftikhar Anjum',
       'Abdur Rehman', 'Younis Khan', 'Mansoor Amjad', 'Wahab Riaz',
       'Mohammad Amir', 'Saeed Ajmal', 'Mohammad Sami', 'Tanvir Ahmed',
       'Junaid Khan', 'Aizaz Cheema', 'Sohail Khan', 'Yasir Shah',
       'Raza Hasan', 'Mohammad Irfan', 'Zulfiqar Babar', 'Asad Ali',
       'Bilawal Bhatti', 'Usman Shinwari', 'Anwar Ali', 'Saad Nasim',
       'Sohaib Maqsood', 'Imad Wasim', 'Imran Khan (1)', 'Ahmed Shehzad',
       'Hasan Ali', 'Mohammad Nawaz (3)', 'Rumman Raees', 'Shadab Khan',
       'Faheem Ashraf', 'Aamer Yamin', 'Hussain Talat',
       'Shaheen Shah Afridi', 'Fakhar Zaman', 'Mohammad Hasnain',
       'Waqas Maqsood', 'Muhammad Musa', 'Haris Rauf', 'Iftikhar Ahmed',
       'Usman Qadir', 'Khushdil Shah', 'Zahid Mahmood', 'Arshad Iqbal',
       'Danish Aziz', 'Mohammad Wasim', 'Mohammad Nawaz',
       'Shahnawaz Dhani', 'Naseem Shah', 'Aamer Jamal', 'Zaman Khan',
       'Ihsanullah'], dtype=object)

In [457]:
rules.sort_values(by='lift', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric,kulczynski_measure,kulczynski measure,jaccard_coefficient,jaccard coefficient
8685,"(Over: 1, 1st Inning, Wickets: 0-1, Lost)","(Shoaib Malik, Economy: 10+)",0.015385,0.018462,0.007692,0.500000,27.083333,0.007408,1.963077,0.978125,0.259231,0.259231,0.294118,0.294118
6944,"(Hong Kong, Won)","(2nd Inning, Over: 2, Economy: 0-6)",0.009231,0.024615,0.006154,0.666667,27.083333,0.005927,2.926154,0.972050,0.345641,0.345641,0.222222,0.222222
8693,"(Over: 1, 1st Inning, Lost)","(Shoaib Malik, Wickets: 0-1, Economy: 10+)",0.015385,0.018462,0.007692,0.500000,27.083333,0.007408,1.963077,0.978125,0.259231,0.259231,0.294118,0.294118
2994,(Hong Kong),"(2nd Inning, Over: 2, Economy: 0-6)",0.009231,0.024615,0.006154,0.666667,27.083333,0.005927,2.926154,0.972050,0.345641,0.345641,0.222222,0.222222
6069,"(Over: 1, 1st Inning, Lost)","(Shoaib Malik, Economy: 10+)",0.015385,0.018462,0.007692,0.500000,27.083333,0.007408,1.963077,0.978125,0.259231,0.259231,0.294118,0.294118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8211,"(Over: 4, West Indies, Won, Economy: 0-6)",(Wickets: 0-1),0.027692,0.689231,0.013846,0.500000,0.725446,-0.005240,0.621538,-0.280182,0.594615,0.594615,0.019694,0.019694
3264,"(Economy: 6-8, 2nd Inning, Haris Rauf)",(Wickets: 0-1),0.012308,0.689231,0.006154,0.500000,0.725446,-0.002329,0.621538,-0.277027,0.594615,0.594615,0.008850,0.008850
997,"(Economy: 0-6, Mohammad Nawaz (3))",(Wickets: 0-1),0.012308,0.689231,0.006154,0.500000,0.725446,-0.002329,0.621538,-0.277027,0.594615,0.594615,0.008850,0.008850
1653,"(Shaheen Shah Afridi, Over: 3)",(Wickets: 0-1),0.012308,0.689231,0.006154,0.500000,0.725446,-0.002329,0.621538,-0.277027,0.594615,0.594615,0.008850,0.008850
8640,"(Over: 4, Won, 1st Inning, Shadab Khan, Econom...",(Wickets: 0-1),0.015385,0.689231,0.007692,0.500000,0.725446,-0.002911,0.621538,-0.277652,0.594615,0.594615,0.011038,0.011038

In [431]:
dataset_size = 205  ## number of matches in the dataset
def calculate_kulczynski_measure(rules):
    precision = rules['confidence']
    recall = rules['consequent support']
    rules['kulczynski_measure'] = (precision + recall) / 2
    return rules['kulczynski_measure']

def calculate_jaccard_coefficient(rules):
    intersection_size = rules['support'] * dataset_size
    union_size = (rules['antecedent support'] * dataset_size) + (rules['consequent support'] * dataset_size) - intersection_size
    rules['jaccard_coefficient'] = intersection_size / union_size
    return rules['jaccard_coefficient']

In [432]:
rules['kulczynski measure'] = calculate_kulczynski_measure(rules)
rules['jaccard coefficient'] = calculate_jaccard_coefficient(rules)

In [433]:
filtered_rules_Lost_antecedents = rules[rules["antecedents"].apply(lambda x: "Lost" in x)]
filtered_rules_Won_antecedents = rules[rules["antecedents"].apply(lambda x: "Won" in x)]

In [434]:
filtered_rules_Lost_antecedents =filtered_rules_Lost_antecedents[['antecedents', 'consequents','confidence','lift', 'jaccard_coefficient', 'kulczynski_measure']]
filtered_rules_Won_antecedents =filtered_rules_Won_antecedents[['antecedents', 'consequents','confidence','lift', 'jaccard_coefficient', 'kulczynski_measure']]

In [435]:
filtered_rules_Lost_cosequents = rules[rules["consequents"].apply(lambda x: "Lost" in x)]
filtered_rules_Won_cosequents = rules[rules["consequents"].apply(lambda x: "Won" in x)]

In [436]:
filtered_rules_Lost_cosequents =filtered_rules_Lost_cosequents[['antecedents', 'consequents','confidence','lift', 'jaccard_coefficient', 'kulczynski_measure']]
filtered_rules_Won_cosequents =filtered_rules_Won_cosequents[['antecedents', 'consequents','confidence','lift', 'jaccard_coefficient', 'kulczynski_measure']]

In [437]:
filtered_rules_Won_cosequents

,antecedents,consequents,confidence,lift,jaccard_coefficient,kulczynski_measure
16,(1st Inning),(Won),0.720000,1.090909,0.421053,0.690000
53,(2nd Inning),(Won),0.608571,0.922078,0.376325,0.634286
57,(Afghanistan),(Won),0.607143,0.919913,0.038636,0.633571
60,(Australia),(Won),0.537037,0.813692,0.063877,0.598519
63,(Bangladesh),(Won),0.965517,1.462905,0.129930,0.812759
...,...,...,...,...,...,...
9069,"(Over: 4, West Indies, Economy: 0-6, Wickets: ...","(Won, Shadab Khan)",0.571429,6.516291,0.066667,0.329560
9071,"(West Indies, Shadab Khan, Economy: 0-6, Wicke...","(Over: 4, Won)",1.000000,2.539062,0.015625,0.696923
9072,"(Over: 4, West Indies, Shadab Khan, Economy: 0-6)","(Won, Wickets: 2-3)",0.571429,2.634245,0.027778,0.394176
9074,"(West Indies, Shadab Khan, Wickets: 2-3)","(Over: 4, Won, Economy: 0-6)",0.800000,5.306122,0.040404,0.475385
9075,"(West Indies, Shadab Khan, Economy: 0-6)","(Over: 4, Won, Wickets: 2-3)",0.500000,3.037383,0.036036,0.332308

In [438]:
filtered_rules_Lost_cosequents

,antecedents,consequents,confidence,lift,jaccard_coefficient,kulczynski_measure
71,(Economy: 10+),(Lost),0.574074,1.688453,0.232210,0.457037
80,(England),(Lost),0.666667,1.960784,0.224900,0.503333
102,(India),(Lost),0.538462,1.583710,0.060086,0.439231
105,(Naseem Shah),(Lost),0.526316,1.547988,0.043478,0.433158
229,"(1st Inning, Economy: 10+)",(Lost),0.500000,1.470588,0.094262,0.420000
...,...,...,...,...,...,...
9030,"(Hasan Ali, Over: 3, Economy: 8-10)","(2nd Inning, Wickets: 0-1, Lost)",0.800000,4.601770,0.035088,0.486923
9033,"(2nd Inning, Wickets: 0-1, Economy: 8-10, Over...",(Lost),1.000000,2.941176,0.018100,0.670000
9037,"(Over: 4, New Zealand, 2nd Inning, Economy: 8-10)","(Wickets: 0-1, Lost)",0.666667,2.420857,0.022099,0.471026
9040,"(Shaheen Shah Afridi, 2nd Inning, Wickets: 0-1...",(Lost),0.571429,1.680672,0.017857,0.455714
9048,"(Shaheen Shah Afridi, Wickets: 0-1, Economy: 8...","(2nd Inning, Lost)",0.500000,2.372263,0.028369,0.355385

In [439]:
filtered_rules_Lost_antecedents

,antecedents,consequents,confidence,lift,jaccard_coefficient,kulczynski_measure
31,(Lost),(2nd Inning),0.619910,1.151261,0.315668,0.579186
106,(Lost),(Over: 4),0.529412,0.922567,0.245283,0.551629
107,(Lost),(Wickets: 0-1),0.809955,1.175158,0.365306,0.749593
313,"(Lost, Mohammad Hafeez)",(1st Inning),0.576923,1.250000,0.048232,0.519231
314,"(Mohammad Hasnain, Lost)",(1st Inning),0.636364,1.378788,0.023026,0.548951
...,...,...,...,...,...,...
9047,"(Shaheen Shah Afridi, 2nd Inning, Lost, Over: 4)","(Wickets: 0-1, Economy: 8-10)",0.571429,3.504043,0.036697,0.367253
9049,"(Shaheen Shah Afridi, Lost, Wickets: 0-1, Econ...","(Over: 4, 2nd Inning)",0.666667,2.380952,0.021739,0.473333
9050,"(Shaheen Shah Afridi, Wickets: 0-1, Lost, Over...","(2nd Inning, Economy: 8-10)",0.666667,5.098039,0.045977,0.398718
9051,"(Shaheen Shah Afridi, Lost, Economy: 8-10, Ove...","(2nd Inning, Wickets: 0-1)",0.800000,2.139918,0.016393,0.586923
9052,"(Shaheen Shah Afridi, Lost, Economy: 8-10)","(Over: 4, 2nd Inning, Wickets: 0-1)",0.571429,3.606103,0.037736,0.364945

In [440]:
filtered_rules_Won_antecedents

,antecedents,consequents,confidence,lift,jaccard_coefficient,kulczynski_measure
15,(Won),(1st Inning),0.503497,1.090909,0.421053,0.482517
149,(Won),(Over: 4),0.596737,1.039890,0.468864,0.585291
169,(Won),(Wickets: 0-1),0.627040,0.909767,0.442434,0.658135
179,"(Won, Afghanistan)",(1st Inning),0.647059,1.401961,0.035948,0.554299
204,"(Won, Bangladesh)",(1st Inning),0.803571,1.741071,0.144695,0.632555
...,...,...,...,...,...,...
9064,"(West Indies, Wickets: 2-3, Over: 4, Won, Econ...",(Shadab Khan),0.571429,4.369748,0.045455,0.351099
9066,"(West Indies, Wickets: 2-3, Won, Shadab Khan, ...",(Over: 4),1.000000,1.742627,0.010724,0.786923
9067,"(West Indies, Over: 4, Won, Shadab Khan, Econo...",(Wickets: 2-3),0.571429,2.052092,0.021739,0.424945
9070,"(West Indies, Won, Shadab Khan, Wickets: 2-3)","(Over: 4, Economy: 0-6)",0.800000,4.000000,0.030534,0.500000
9073,"(West Indies, Won, Shadab Khan, Economy: 0-6)","(Over: 4, Wickets: 2-3)",0.500000,2.304965,0.027586,0.358462

In [441]:
filtered_rules_Won_cosequents = filtered_rules_Won_cosequents[filtered_rules_Won_cosequents['consequents'].apply(lambda x: any(bowler in x for bowler in bowler_list))]
filtered_rules_Lost_cosequents = filtered_rules_Lost_cosequents[filtered_rules_Lost_cosequents['consequents'].apply(lambda x: any(bowler in x for bowler in bowler_list))]

In [442]:
filtered_rules_Won = filtered_rules_Won_cosequents
filtered_rules_Lost = filtered_rules_Lost_cosequents

In [443]:
filtered_rules_Won.sort_values(by=['confidence'], ascending=False)

,antecedents,consequents,confidence,lift,jaccard_coefficient,kulczynski_measure
4276,"(Bangladesh, Over: 2)","(Shoaib Malik, Won)",0.625000,13.541667,0.151515,0.335577
5921,"(Over: 1, 1st Inning, Economy: 0-6)","(Shoaib Malik, Won)",0.571429,12.380952,0.121212,0.308791
8633,"(Over: 1, 1st Inning, Wickets: 0-1, Economy: 0-6)","(Shoaib Malik, Won)",0.571429,12.380952,0.121212,0.308791
8636,"(Over: 1, 1st Inning, Economy: 0-6)","(Shoaib Malik, Won, Wickets: 0-1)",0.571429,14.857143,0.142857,0.304945
9069,"(Over: 4, West Indies, Economy: 0-6, Wickets: ...","(Won, Shadab Khan)",0.571429,6.516291,0.066667,0.329560
7027,"(Zimbabwe, 2nd Inning, Economy: 0-6)","(Won, Mohammad Hafeez)",0.555556,7.850242,0.100000,0.313162
7183,"(Wickets: 3+, 2nd Inning, Economy: 0-6)","(Won, Shadab Khan)",0.500000,5.701754,0.065574,0.293846

In [444]:
filtered_rules_Lost.sort_values(by=['confidence'], ascending=False)

Empty DataFrame
Columns: [antecedents, consequents, confidence, lift, jaccard_coefficient, kulczynski_measure]
Index: []

In [445]:
# First, normalize the columns. Here we'll use min-max normalization.
for column in ['confidence', 'lift', 'jaccard_coefficient', 'kulczynski_measure']:
    filtered_rules_Won[column + '_norm'] = (filtered_rules_Won[column] - filtered_rules_Won[column].min()) / (filtered_rules_Won[column].max() - filtered_rules_Won[column].min())

# Assign weights to the attributes based on their importance.
weights = {
    'confidence_norm': 0.30,
    'lift_norm': 0.10,
    'jaccard_coefficient_norm': 0.30,
    'kulczynski_measure_norm': 0.30
}

# Calculate the weighted score for each association rule.
filtered_rules_Won['score'] = sum(filtered_rules_Won[attribute] * weight for attribute, weight in weights.items())

# Sort the DataFrame based on the score in descending order to rank the rules.
filtered_rules_Won = filtered_rules_Won.sort_values(by='score', ascending=False)

#association rules ranked by their score.

/tmp/ipykernel_20988/725498372.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_rules_Won[column + '_norm'] = (filtered_rules_Won[column] - filtered_rules_Won[column].min()) / (filtered_rules_Won[column].max() - filtered_rules_Won[column].min())
/tmp/ipykernel_20988/725498372.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_rules_Won[column + '_norm'] = (filtered_rules_Won[column] - filtered_rules_Won[column].min()) / (filtered_rules_Won[column].max() - filtered_rules_Won[column].min())
/tmp/ipykernel_20988/725498372.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_rules_Won[column + '_norm'] = (filtered_rules_Won[column] - filtered_rules_Won[column].min()) / (filtered_rules_Won[column].max() - filtered_rules_Won[column].min())
/tmp/ipykernel_20988/725498372.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_rules_Won[column + '_norm'] = (filtered_rules_Won[column] - filtered_rules_Won[column].min()) / (filtered_rules_Won[column].max() - filtered_rules_Won[column].min())
/tmp/ipykernel_20988/725498372.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_rules_Won['score'] = sum(filtered_rules_Won[attribute] * weight for attribute, weight in weights.items())

In [446]:
# First, normalize the columns. Here we'll use min-max normalization.
for column in ['confidence', 'lift', 'jaccard_coefficient', 'kulczynski_measure']:
    filtered_rules_Lost[column + '_norm'] = (filtered_rules_Lost[column] - filtered_rules_Lost[column].min()) / (filtered_rules_Lost[column].max() - filtered_rules_Lost[column].min())

# Assign weights to the attributes based on their importance.
weights = {
    'confidence_norm': 0.30,
    'lift_norm': 0.10,
    'jaccard_coefficient_norm': 0.30,
    'kulczynski_measure_norm': 0.30
}

# Calculate the weighted score for each association rule.
filtered_rules_Lost['score'] = sum(filtered_rules_Lost[attribute] * weight for attribute, weight in weights.items())

# Sort the DataFrame based on the score in descending order to rank the rules.
filtered_rules_Lost = filtered_rules_Lost.sort_values(by='score', ascending=False)

#association rules ranked by their score.

In [447]:
filtered_rules_Lost

Empty DataFrame
Columns: [antecedents, consequents, confidence, lift, jaccard_coefficient, kulczynski_measure, confidence_norm, lift_norm, jaccard_coefficient_norm, kulczynski_measure_norm, score]
Index: []

In [448]:
filtered_rules_Won

,antecedents,consequents,confidence,lift,jaccard_coefficient,kulczynski_measure,confidence_norm,lift_norm,jaccard_coefficient_norm,kulczynski_measure_norm,score
4276,"(Bangladesh, Over: 2)","(Shoaib Malik, Won)",0.625000,13.541667,0.151515,0.335577,1.000000,0.856317,1.000000,1.000000,0.985632
8636,"(Over: 1, 1st Inning, Economy: 0-6)","(Shoaib Malik, Won, Wickets: 0-1)",0.571429,14.857143,0.142857,0.304945,0.571429,1.000000,0.899257,0.265964,0.620995
5921,"(Over: 1, 1st Inning, Economy: 0-6)","(Shoaib Malik, Won)",0.571429,12.380952,0.121212,0.308791,0.571429,0.729537,0.647399,0.358130,0.546041
8633,"(Over: 1, 1st Inning, Wickets: 0-1, Economy: 0-6)","(Shoaib Malik, Won)",0.571429,12.380952,0.121212,0.308791,0.571429,0.729537,0.647399,0.358130,0.546041
9069,"(Over: 4, West Indies, Economy: 0-6, Wickets: ...","(Won, Shadab Khan)",0.571429,6.516291,0.066667,0.329560,0.571429,0.088968,0.012717,0.855826,0.440888
7027,"(Zimbabwe, 2nd Inning, Economy: 0-6)","(Won, Mohammad Hafeez)",0.555556,7.850242,0.100000,0.313162,0.444444,0.234669,0.400578,0.462878,0.415837
7183,"(Wickets: 3+, 2nd Inning, Economy: 0-6)","(Won, Shadab Khan)",0.500000,5.701754,0.065574,0.293846,0.000000,0.000000,0.000000,0.000000,0.000000

In [449]:
def filter_rules(rules, bowler_name):
    filtered_rules = rules[rules["antecedents"].apply(lambda x: bowler_name in x)]
    return filtered_rules

#### Filtering Rules for top 10 bowlers based on matches played

In [450]:
top10_bowler_list

Index(['Shadab Khan', 'Mohammad Hafeez', 'Imad Wasim', 'Haris Rauf',
       'Shaheen Shah Afridi', 'Hasan Ali', 'Faheem Ashraf', 'Shoaib Malik',
       'Mohammad Nawaz', 'Mohammad Hasnain'],
      dtype='object', name='Bowler')

For Shadab Khan

In [451]:
## for Shadab Khan
rules_for_shadab_khan =filter_rules(filtered_rules_Won, "Shadab Khan")
rules_for_shadab_khan[rules_for_shadab_khan["consequents"].apply(lambda x: "Lost" in x)]

Empty DataFrame
Columns: []
Index: []